CREATE DATABASE CONSULTORIO;

USE CONSULTORIO;

CREATE TABLE PACIENTE(
	IDPACIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	SEXO CHAR(1),
	EMAIL VARCHAR(30),
	NASCIMENTO DATE
	);

CREATE TABLE MEDICO(
	IDMEDICO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	SEXO CHAR(1),
	ESPECIALIDADE VARCHAR(30),
	FUNCIONARIO ENUM('S','N')
	);

CREATE TABLE HOSPITAL(
	IDHOSPITAL INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	BAIRRO VARCHAR(30),
	CIDADE VARCHAR(30),
	ESTADO CHAR(2)
	);

CREATE TABLE CONSULTA(
	IDCONSULTA INT PRIMARY KEY AUTO_INCREMENT,
	ID_PACIENTE INT,
	ID_MEDICO INT,
	ID_HOSPITAL INT,
	DATA DATETIME,
	DIAGNOSTICO VARCHAR(50)
	);

CREATE TABLE INTERNACAO(
	IDINTERNACAO INT PRIMARY KEY AUTO_INCREMENT,
	ENTRADA DATETIME,
	QUARTO INT,
	OBSERVACOES VARCHAR(30),
	ID_CONSULTA INT UNIQUE
	);

/*CRIANDO AS CONSTRAINTS
COD DO OBJ (PK, FK) _TABELA PERTENCENTE _ TABELA DE ONDE VEM
PK - PRIMARY KEY
FK - FOREINGN KEY
*/

ALTER TABLE CONSULTA ADD CONSTRAINT FK_CONSULTA_PACIENTE
	FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE(IDPACIENTE);

ALTER TABLE CONSULTA ADD CONSTRAINT FK_CONSULTA_MEDICO
	FOREIGN KEY (ID_MEDICO) REFERENCES MEDICO(IDMEDICO);

ALTER TABLE CONSULTA ADD CONSTRAINT FK_CONSULTA_HOSPITAL
	FOREIGN KEY (ID_HOSPITAL) REFERENCES HOSPITAL(IDHOSPITAL);

ALTER TABLE INTERNACAO ADD CONSTRAINT FK_INTERNACAO_CONSULTA
	FOREIGN KEY (ID_CONSULTA) REFERENCES CONSULTA(IDCONSULTA);

/*APAGANDO UMA CONSTRAINT */

--NOS COMANDOS ABAIXO HAVIA ERRADO A NOMECLATURA PK_ AO INVES DE FK
ALTER TABLE CONSULTA
	DROP FOREIGN KEY PK_CONSULTA_PACIENTE;
ALTER TABLE CONSULTA
	DROP FOREIGN KEY PK_CONSULTA_MEDICO;
ALTER TABLE CONSULTA
	DROP FOREIGN KEY PK_CONSULTA_HOSPITAL;
ALTER TABLE INTERNACAO
	DROP FOREIGN KEY FK_INTERNACAO_CONSULTA;

SHOW CREATE TABLE PACIENTE;
SHOW CREATE TABLE MEDICO;
SHOW CREATE TABLE HOSPITAL;
SHOW CREATE TABLE INTERNACAO;
SHOW CREATE TABLE CONSULTA;


mysql> SHOW CREATE TABLE PACIENTE;SHOW CREATE TABLE MEDICO;SHOW CREATE TABLE HOSPITAL;SHOW CREATE TABLE INTERNACAO;SHOW CREATE TABLE CONSULTA;

| INTERNACAO | CREATE TABLE `internacao` (
  `IDINTERNACAO` int(11) NOT NULL AUTO_INCREMENT,
  `ENTRADA` datetime DEFAULT NULL,
  `QUARTO` int(11) DEFAULT NULL,
  `OBSERVACOES` varchar(30) DEFAULT NULL,
  `ID_CONSULTA` int(11) DEFAULT NULL,
  PRIMARY KEY (`IDINTERNACAO`),
  UNIQUE KEY `ID_CONSULTA` (`ID_CONSULTA`),
  CONSTRAINT `FK_INTERNACAO_CONSULTA` FOREIGN KEY (`ID_CONSULTA`) REFERENCES `consulta` (`IDCONSULTA`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 |
+------------+---------------------------------------------------------------------------------------------

) ENGINE=InnoDB DEFAULT CHARSET=latin1 |
+--------+
1 row in set (0.00 sec)

/*ERRADA  - HAVIA NOMEADO AS CHAVES ESTRANGERIAS COMO PK AO INVES DE FK (NO EX ABAIXO ESTA CORRETO)*/
| CONSULTA | CREATE TABLE `consulta` (
  `IDCONSULTA` int(11) NOT NULL AUTO_INCREMENT,
  `ID_PACIENTE` int(11) DEFAULT NULL,
  `ID_MEDICO` int(11) DEFAULT NULL,
  `ID_HOSPITAL` int(11) DEFAULT NULL,
  `DATA` datetime DEFAULT NULL,
  `DIAGNOSTICO` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`IDCONSULTA`),
  KEY `PK_CONSULTA_PACIENTE` (`ID_PACIENTE`),
  KEY `PK_CONSULTA_MEDICO` (`ID_MEDICO`),
  KEY `PK_CONSULTA_HOSPITAL` (`ID_HOSPITAL`),
  CONSTRAINT `PK_CONSULTA_HOSPITAL` FOREIGN KEY (`ID_HOSPITAL`) REFERENCES `hospital` (`IDHOSPITAL`),
  CONSTRAINT `PK_CONSULTA_MEDICO` FOREIGN KEY (`ID_MEDICO`) REFERENCES `medico` (`IDMEDICO`),
  CONSTRAINT `PK_CONSULTA_PACIENTE` FOREIGN KEY (`ID_PACIENTE`) REFERENCES `paciente` (`IDPACIENTE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 |

/*CORRETA*/
-------------------------------------------------------------------------------------------------------
---------------------------------------------------------+
| CONSULTA | CREATE TABLE `consulta` (
  `IDCONSULTA` int(11) NOT NULL AUTO_INCREMENT,
  `ID_PACIENTE` int(11) DEFAULT NULL,
  `ID_MEDICO` int(11) DEFAULT NULL,
  `ID_HOSPITAL` int(11) DEFAULT NULL,
  `DATA` datetime DEFAULT NULL,
  `DIAGNOSTICO` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`IDCONSULTA`),
  KEY `FK_CONSULTA_PACIENTE` (`ID_PACIENTE`),
  KEY `FK_CONSULTA_MEDICO` (`ID_MEDICO`),
  KEY `FK_CONSULTA_HOSPITAL` (`ID_HOSPITAL`),
  CONSTRAINT `FK_CONSULTA_HOSPITAL` FOREIGN KEY (`ID_HOSPITAL`) REFERENCES `hospital` (`IDHOSPITAL`),
  CONSTRAINT `FK_CONSULTA_MEDICO` FOREIGN KEY (`ID_MEDICO`) REFERENCES `medico` (`IDMEDICO`),
  CONSTRAINT `FK_CONSULTA_PACIENTE` FOREIGN KEY (`ID_PACIENTE`) REFERENCES `paciente` (`IDPACIENTE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 |
+----------+
1 row in set (0.01 sec)

--LOCALIZAR AS FOREINGN KEY NO BANCO

SHOW DATABASES;
USE INFORMATION_SCHEMA;
SHOW TABLES;
TABLE DESC TABLE_CONSTRAINT;
SELECT * FROM TABLE_CONSTRAINTS
	ORDER BY CONSTRAINT_NAME;