
CREATE DATABASE COMERCIO;

USE COMERCIO;

DROP TABLE CLIENTE;
TRUNCATE TABLE CLIENTE;

CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	SEXO ENUM('M', 'F') NOT NULL,
	EMAIL VARCHAR(50) UNIQUE
	CPF VARCHAR(15) UNIQUE
);

/*DESTAQUE DA AULA*/
ENUM - USADO SOMENTE NO MYSQL (DOMINIO, INFORMAÇÕES FIXA EX. SEXO F OU M)
UNIQUE - COMANDO PARA DIZER QUE OS VALORES SÃO UNICO E NÃO SE REPETE

CREATE TABLE ENDERECO(
	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
	RUA VARCHAR(30) NOT NULL,
	BAIRRO VARCHAR(30) NOT NULL,
	CIDADE VARCHAR(30) NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	ID_CLIENTE INT UNIQUE,

	FOREIGN KEY(ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)
);

CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM ('RES','COM','CEL') NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	ID_CLIENTE INT,

	FOREIGN KEY(ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)
);

SELECT * FROM CLIENTE;

INSERT INTO CLIENTE VALUES (NULL, 'JOAO','M','JOAO@IG.COM','12345678913'),
						   (NULL, 'CARLOS','M','CARLOS@HOTMAIL.COM','30345678914'),
						   (NULL, 'ANA','F','ANA@GMAIL.COM','120345678915'),
						   (NULL, 'CLARA','F',NULL,'40345678916'),
						   (NULL, 'JORGE','M','JORGE@BOL.COM','50345678917'),
						   (NULL, 'CELIA','F','CELIA@YAHOO.COM','60345678918'),
						   (NULL, 'CASSIO','M','CASSIO@OUTLOOK.COM','70345678919');

mysql> SELECT * FROM CLIENTE;
+-----------+--------+------+--------------------+--------------+
| IDCLIENTE | NOME   | SEXO | EMAIL              | CPF          |
+-----------+--------+------+--------------------+--------------+
|         1 | JOAO   | M    | JOAO@IG.COM        | 12345678910  |
|         2 | CARLOS | M    | CARLOS@HOTMAIL.COM | 30345678914  |
|         3 | ANA    | F    | ANA@GMAIL.COM      | 120345678915 |
|         4 | CLARA  | F    | NULL               | 40345678916  |
|         5 | JORGE  | M    | JORGE@BOL.COM      | 50345678917  |
|         6 | CELIA  | F    | CELIA@YAHOO.COM    | 60345678918  |
|         7 | CASSIO | M    | CASSIO@OUTLOOK.COM | 70345678919  |
+-----------+--------+------+--------------------+--------------+

DESC ENDERECO;

INSERT INTO ENDERECO VALUES (NULL,'AV PAULISTA','CENTRO','SAO PAULO','SP',4);
INSERT INTO ENDERECO VALUES (NULL,'RUA BELORIZONTINA','BARREIRO','B.HORIZONTE','MG',1);
INSERT INTO ENDERECO VALUES (NULL,'AV CERVANEJA','EIXO NORTE','GOIANIA','GO',3);
INSERT INTO ENDERECO VALUES (NULL,'AV NORTE SUL','JARDIM CAMBURI','VITORIA','ES',2);
INSERT INTO ENDERECO VALUES (NULL,'RUA DOS BAIANOS','ESTACIO','RIO DE JANEIRO','RJ',6);
INSERT INTO ENDERECO VALUES (NULL,'AV BRASIL','COPACABANA','RIO DE JANEIRO','RJ',5);
INSERT INTO ENDERECO VALUES (NULL,'RUA STA EFIGENIA','JD CLAUDIA','S B CAMPO','SP',7);

mysql> SELECT * FROM ENDERECO;
+------------+-------------------+----------------+----------------+--------+------------+
| IDENDERECO | RUA               | BAIRRO         | CIDADE         | ESTADO | ID_CLIENTE |
+------------+-------------------+----------------+----------------+--------+------------+
|          1 | AV PAULISTA       | CENTRO         | SAO PAULO      | SP     |          4 |
|          2 | RUA BELORIZONTINA | BARREIRO       | B.HORIZONTE    | MG     |          1 |
|          3 | AV CERVANEJA      | EIXO NORTE     | GOIANIA        | GO     |          3 |
|          4 | AV NORTE SUL      | JARDIM CAMBURI | VITORIA        | ES     |          2 |
|          5 | RUA DOS BAIANOS   | ESTACIO        | RIO DE JANEIRO | RJ     |          6 |
|          6 | AV BRASIL         | COPACABANA     | RIO DE JANEIRO | RJ     |          5 |
|          7 | RUA STA EFIGENIA  | JD CLAUDIA     | S B CAMPO      | SP     |          7 |
+------------+-------------------+----------------+----------------+--------+------------+
7 rows in set (0.00 s


TRUNCATE TABLE TELEFONE;
DESC TELEFONE;
SELECT * FROM CLIENTE;

SELECT * FROM TELEFONE ORDER BY ID_CLIENTE;


INSERT INTO TELEFONE VALUES (NULL,'CEL','966695313',7);
INSERT INTO TELEFONE VALUES (NULL,'COM','080070070',6);
INSERT INTO TELEFONE VALUES (NULL,'RES','43516032',2);
INSERT INTO TELEFONE VALUES (NULL,'CEL','984206159',4);
INSERT INTO TELEFONE VALUES (NULL,'COM','30305050',4);
INSERT INTO TELEFONE VALUES (NULL,'RES','41206580',2);
INSERT INTO TELEFONE VALUES (NULL,'CEL','708425624',7);
INSERT INTO TELEFONE VALUES (NULL,'COM','809251942',3);
INSERT INTO TELEFONE VALUES (NULL,'CEL','506238282',7);

CLIENTE 1, 5 SEM TELEFONE

SELECAO, PROJECAO E JUNCAO

PROJECAO -> E TUDO QUE VC QUER VER NA TELA

SELECT NOW() AS DATA_ATUAL;

SELECT 2 + 2 AS SOMA;

SELECT 2 + 2 AS SOMA, NOME, NOW()
FROM CLIENTE;

SELECAO -> E UM SUBCONJUNTO DO CONJUNTO TOTAL DE REGISTROS DE UMA TABELA A CLAUSULA DA SELECAO E O WHERE

SELECT NOME, SEXO, EMAIL /*PROJECAO*/
FROM CLIENTE; 			 /*ORIGEM*/
WHERE SEXO = 'F'; 		 /*SELECAO*/

SELECT NUMERO    /*PROJECAO*/
FROM TELEFONE    /*ORIGEM*/
WHERE TIPO = 'CEL'; /*SELECAO*/

/* JUNCAO -> JOIN */


mysql> SELECT NOME, EMAIL, IDCLIENTE FROM CLIENTE;
+------------+----------------+----------------+
| ID_CLIENTE | BAIRRO         | CIDADE         |
+------------+----------------+----------------+
|          4 | CENTRO         | SAO PAULO      |
|          1 | BARREIRO       | B.HORIZONTE    |
|          3 | EIXO NORTE     | GOIANIA        |
|          2 | JARDIM CAMBURI | VITORIA        |
|          6 | ESTACIO        | RIO DE JANEIRO |
|          5 | COPACABANA     | RIO DE JANEIRO |
|          7 | JD CLAUDIA     | S B CAMPO      |
+------------+----------------+----------------+
7 rows in set (0.00 sec)

mysql> SELECT NOME, EMAIL, IDCLIENTE FROM CLIENTE;
+--------+--------------------+-----------+
| NOME   | EMAIL              | IDCLIENTE |
+--------+--------------------+-----------+
| JOAO   | JOAO@IG.COM        |         1 |
| CARLOS | CARLOS@HOTMAIL.COM |         2 |
| ANA    | ANA@GMAIL.COM      |         3 |
| CLARA  | NULL               |         4 |
| JORGE  | JORGE@BOL.COM      |         5 |
| CELIA  | CELIA@YAHOO.COM    |         6 |
| CASSIO | CASSIO@OUTLOOK.COM |         7 |
+--------+--------------------+-----------+
7 rows in set (0.01 sec)

SELECT NOME, SEXO, BAIRRO, CIDADE 
FROM CLIENTE, ENDERECO 
WHERE IDCLIENTE = ID_CLIENTE;


SELECT NOME, SEXO, BAIRRO, CIDADE 
FROM CLIENTE, ENDERECO 
WHERE IDCLIENTE = ID_CLIENTE;

mysql> SELECT NOME, SEXO, BAIRRO, CIDADE FROM CLIENTE, ENDERECO
+--------+------+----------------+----------------+
| NOME   | SEXO | BAIRRO         | CIDADE         |
+--------+------+----------------+----------------+
| JOAO   | M    | BARREIRO       | B.HORIZONTE    |
| CARLOS | M    | JARDIM CAMBURI | VITORIA        |
| ANA    | F    | EIXO NORTE     | GOIANIA        |
| CLARA  | F    | CENTRO         | SAO PAULO      |
| JORGE  | M    | COPACABANA     | RIO DE JANEIRO |
| CELIA  | F    | ESTACIO        | RIO DE JANEIRO |
| CASSIO | M    | JD CLAUDIA     | S B CAMPO      |
+--------+------+----------------+----------------+
7 rows in set (0.00 sec)

/*WHERE = SELECAO*/

SELECT NOME, SEXO, BAIRRO, CIDADE 
FROM CLIENTE, ENDERECO 
WHERE IDCLIENTE = ID_CLIENTE 
AND SEXO = 'F';

mysql> SELECT NOME, SEXO, BAIRRO, CIDADE FROM CLIENTE, ENDERECO WHERE IDCLIENTE = ID_CLIENTE AND SEXO = 'F';
+-------+------+------------+----------------+
| NOME  | SEXO | BAIRRO     | CIDADE         |
+-------+------+------------+----------------+
| ANA   | F    | EIXO NORTE | GOIANIA        |
| CLARA | F    | CENTRO     | SAO PAULO      |
| CELIA | F    | ESTACIO    | RIO DE JANEIRO |
+-------+------+------------+----------------+
3 rows in set (0.00 sec)

/*
WHERE IDCLIENTE = ID_CLIENTE 
AND SEXO = 'F'; -> USANDO TABELA VERDADE
*/

JOIN E JUNCAO


SELECT NOME, SEXO, BAIRRO, CIDADE 
FROM CLIENTE 
INNER JOIN ENDERECO /*ME JUNTE COM NOME_DA_TABELA*/
ON IDCLIENTE = ID_CLIENTE; /*ONDE ID TAL SEJA IGUAL A ID TAL */

SELECT NOME, SEXO, BAIRRO, CIDADE
 FROM CLIENTE
 INNER JOIN ENDERECO
 ON IDCLIENTE = ID_CLIENTE;


mysql> SELECT NOME, SEXO, BAIRRO, CIDADE FROM CLIENTE INNER JOIN ENDERECO ON IDCLIENTE = ID_CLIENTE;
+--------+------+----------------+----------------+
| NOME   | SEXO | BAIRRO         | CIDADE         |
+--------+------+----------------+----------------+
| JOAO   | M    | BARREIRO       | B.HORIZONTE    |
| CARLOS | M    | JARDIM CAMBURI | VITORIA        |
| ANA    | F    | EIXO NORTE     | GOIANIA        |
| CLARA  | F    | CENTRO         | SAO PAULO      |
| JORGE  | M    | COPACABANA     | RIO DE JANEIRO |
| CELIA  | F    | ESTACIO        | RIO DE JANEIRO |
| CASSIO | M    | JD CLAUDIA     | S B CAMPO      |
+--------+------+----------------+----------------+
7 rows in set (0.01 sec)

SELECT NOME, SEXO, BAIRRO, CIDADE 	/*PROJECAO*/ 
 FROM CLIENTE						/*ORIGEM*/
 INNER JOIN IDENDERECO				/*JUNCAO*/
 ON IDCLIENTE = ID_CLIENTE
 WHERE SEXO = 'F';					/*SELECAO*/

mysql> SELECT NOME, SEXO, BAIRRO, CIDADE FROM CLIENTE INNER JOIN ENDERECO ON IDCLIENTE = ID_CLIENTE WHERE SEXO = 'F';
+-------+------+------------+----------------+
| NOME  | SEXO | BAIRRO     | CIDADE         |
+-------+------+------------+----------------+
| ANA   | F    | EIXO NORTE | GOIANIA        |
| CLARA | F    | CENTRO     | SAO PAULO      |
| CELIA | F    | ESTACIO    | RIO DE JANEIRO |
+-------+------+------------+----------------+
3 rows in set (0.00 sec)

/*TABELA 1 X N*/

SELECT NOME, SEXO, EMAIL, TIPO, NUMERO
	FROM CLIENTE
	INNER JOIN TELEFONE
	ON IDCLIENTE = ID_CLIENTE;  /*IDCLIENTE É CHAVE PRIMAIRA E ID_CLIENTE É CAHAVE ESTRANGEIRA(FK)*/

mysql> SELECT NOME, SEXO, EMAIL, TIPO, NUMERO   FROM CLIENTE    INNER JOIN TELEFONE     ON IDCLIENTE = ID_CLIENTE;
+--------+------+--------------------+------+-----------+
| NOME   | SEXO | EMAIL              | TIPO | NUMERO    |
+--------+------+--------------------+------+-----------+
| CASSIO | M    | CASSIO@OUTLOOK.COM | CEL  | 966695313 |
| CELIA  | F    | CELIA@YAHOO.COM    | COM  | 080070070 |
| CARLOS | M    | CARLOS@HOTMAIL.COM | RES  | 43516032  |
| CLARA  | F    | NULL               | CEL  | 984206159 |
| CLARA  | F    | NULL               | COM  | 30305050  |
| CARLOS | M    | CARLOS@HOTMAIL.COM | RES  | 41206580  |
| CASSIO | M    | CASSIO@OUTLOOK.COM | CEL  | 708425624 |
| ANA    | F    | ANA@GMAIL.COM      | COM  | 809251942 |
| CASSIO | M    | CASSIO@OUTLOOK.COM | CEL  | 506238282 |
+--------+------+--------------------+------+-----------+
9 rows in set (0.00 sec)

/*JUNCAO DE MAIS DE DUAS TABELAS COM INNER JOIN*/

/*MANEIRA INCORRETA VALOREES AMBIGUOS DEVIDO A TABELA ID_CLIENTE*/
SELECT NOME, SEXO, BAIRRO, CIDADE, TIPO, NUMERO
	FROM CLIENTE
	INNER JOIN ENDERECO
	ON IDCLIENTE = ID_CLIENTE
	INNER JOIN TELEFONE
	ON IDCLIENTE = ID_CLIENTE;

/*MANEIRA CORRETA, RENOMEAR CADA COLUNA REFERENCIANDO A SUA TABELA*/
SELECT CLIENTE.NOME, CLIENTE.SEXO, ENDERECO.BAIRRO, ENDERECO.CIDADE, TELEFONE.TIPO, TELEFONE.NUMERO
	FROM CLIENTE
	INNER JOIN ENDERECO
	ON CLIENTE.IDCLIENTE = ENDERECO.ID_CLIENTE
	INNER JOIN TELEFONE
	ON CLIENTE.IDCLIENTE = TELEFONE.ID_CLIENTE;

mysql> SELECT CLIENTE.NOME, CLIENTE.SEXO, ENDERECO.BAIRRO, ENDERECO.CIDADE, TELEFONE.TIPO, TELEFONE.NUMERO      FROM CLIENTE    INNER JOIN ENDERECO     ON CLIENTE.IDCLIENTE = ENDER
ECO.ID_CLIENTE  INNER JOIN TELEFONE     ON CLIENTE.IDCLIENTE = TELEFONE.ID_CLIENTE;
+--------+------+----------------+----------------+------+-----------+
| NOME   | SEXO | BAIRRO         | CIDADE         | TIPO | NUMERO    |
+--------+------+----------------+----------------+------+-----------+
| CARLOS | M    | JARDIM CAMBURI | VITORIA        | RES  | 43516032  |
| CARLOS | M    | JARDIM CAMBURI | VITORIA        | RES  | 41206580  |
| ANA    | F    | EIXO NORTE     | GOIANIA        | COM  | 809251942 |
| CLARA  | F    | CENTRO         | SAO PAULO      | CEL  | 984206159 |
| CLARA  | F    | CENTRO         | SAO PAULO      | COM  | 30305050  |
| CELIA  | F    | ESTACIO        | RIO DE JANEIRO | COM  | 080070070 |
| CASSIO | M    | JD CLAUDIA     | S B CAMPO      | CEL  | 966695313 |
| CASSIO | M    | JD CLAUDIA     | S B CAMPO      | CEL  | 708425624 |
| CASSIO | M    | JD CLAUDIA     | S B CAMPO      | CEL  | 506238282 |
+--------+------+----------------+----------------+------+-----------+
9 rows in set (0.04 sec)

PONTEIRAMENTO AJUDA NA PERFOMANCE, EM BUSCA NO BANCO ELE SO VAI ATRAS DAS COLUNA PONTEIRADA
/* OUTRA MANEIRA DE OBTER O RESULTADO */ - PONTEIRAMENTO 
SELECT C.NOME, C.SEXO, E.BAIRRO, E.CIDADE, T.TIPO, T.NUMERO
	FROM CLIENTE C
	INNER JOIN ENDERECO E
	ON C.IDCLIENTE = E.ID_CLIENTE
	INNER JOIN TELEFONE T
	ON C.IDCLIENTE = T.ID_CLIENTE;

mysql> SELECT C.NOME, C.SEXO, E.BAIRRO, E.CIDADE, T.TIPO, T.NUMERO      FROM CLIENTE C  INNER JOIN ENDERECO E   ON C.IDCLIENTE = E.ID_CLIENTE   INNER JOIN TELEFONE T   ON C.IDCLIEN
TE = T.ID_CLIENTE;
+--------+------+----------------+----------------+------+-----------+
| NOME   | SEXO | BAIRRO         | CIDADE         | TIPO | NUMERO    |
+--------+------+----------------+----------------+------+-----------+
| CARLOS | M    | JARDIM CAMBURI | VITORIA        | RES  | 43516032  |
| CARLOS | M    | JARDIM CAMBURI | VITORIA        | RES  | 41206580  |
| ANA    | F    | EIXO NORTE     | GOIANIA        | COM  | 809251942 |
| CLARA  | F    | CENTRO         | SAO PAULO      | CEL  | 984206159 |
| CLARA  | F    | CENTRO         | SAO PAULO      | COM  | 30305050  |
| CELIA  | F    | ESTACIO        | RIO DE JANEIRO | COM  | 080070070 |
| CASSIO | M    | JD CLAUDIA     | S B CAMPO      | CEL  | 966695313 |
| CASSIO | M    | JD CLAUDIA     | S B CAMPO      | CEL  | 708425624 |
| CASSIO | M    | JD CLAUDIA     | S B CAMPO      | CEL  | 506238282 |
+--------+------+----------------+----------------+------+-----------+
9 rows in set (0.01 sec)


INSERT INTO CLIENTE (IDCLIENTE, NOME, SEXO, EMAIL, CPF) VALUES (NULL, 'MARIANA', 'F', 'MNIKE@GMAIL.COM', '52345678933');
INSERT INTO ENDERECO (RUA, BAIRRO, CIDADE, ESTADO, IDENDERECO) VALUES ('RUA SANTO ANDRE','ANDRE CARLONE','SERRA','ES',8);
INSERT INTO TELEFONE (TIPO, NUMERO, IDTELEFONE) VALUES ('CEL','27970809020',8);

DESC CLIENTE;
DESC ENDERECO;
DESC TELEFONE;

SELECT * FROM CLIENTE ORDER BY IDCLIENTE;

SELECT * FROM CLIENTE;
SELECT * FROM ENDERECO;
SELECT * FROM TELEFONE;

/*--ERRADO 

PRATICANDO AS QUERY COM INNER JOIN
SELECT C.IDCLIENTE, C.NOME, .C.SEXO, .C.EMAIL, E.CIDADE, E.ESTADO, T.TIPO, T.NUMERO, E.ID_CLIENTE, T.ID_CLIENTE
 FROM CLIENTE C
 INNER JOIN ENDERECO E
 ON C.IDCLIENTE = E.ID_CLIENTE AND C.IDCLIENTE = 8
 INNER JOIN TELEFONE T
 ON C.IDCLIENTE = T.ID_CLIENTE AND C.IDCLIENTE = 8;

SELECT C.IDCLIENTE, C.NOME, .C.SEXO, .C.EMAIL, E.CIDADE, E.ESTADO, T.TIPO, T.NUMERO, E.ID_CLIENTE, T.ID_CLIENTE
 FROM CLIENTE C, ENDERECO E, TELEFONE T
 WHERE IDCLIENTE = 8 AND (E.ID_CLIENTE AND T.ID_CLIENTE);

UPDATE ENDERECO SET ID_CLIENTE = 8 WHERE IDENDERECO = 8;


SELECT IDCLIENTE, C.NOME, C.SEXO, E.BAIRRO, E.CIDADE, T.TIPO, T.NUMERO, T.ID_CLIENTE, E.ID_CLIENTE
	FROM CLIENTE C
	INNER JOIN ENDERECO E
	ON C.IDCLIENTE = E.ID_CLIENTE
	INNER JOIN TELEFONE T
	ON C.IDCLIENTE = T.ID_CLIENTE
	ORDER BY IDCLIENTE;
*/


/* EXERCICIOS DML */

INSERT INTO CLIENTE VALUES(NULL,'FLAVIO','M','FLAVIO@IG.COM','4657765');
INSERT INTO CLIENTE VALUES(NULL,'ANDRE','M','ANDRE@GLOBO.COM','7687567');
INSERT INTO CLIENTE VALUES(NULL,'GIOVANA','F',NULL,'0876655');
INSERT INTO CLIENTE VALUES(NULL,'KARLA','M','KARLA@GMAIL.COM','545676778');
INSERT INTO CLIENTE VALUES(NULL,'DANIELE','M','DANIELE@GMAIL.COM','43536789');
INSERT INTO CLIENTE VALUES(NULL,'LORENA','M',NULL,'774557887');
INSERT INTO CLIENTE VALUES(NULL,'EDUARDO','M',NULL,'54376457');
INSERT INTO CLIENTE VALUES(NULL,'ANTONIO','F','ANTONIO@IG.COM','12436767');
INSERT INTO CLIENTE VALUES(NULL,'ANTONIO','M','ANTONIO@UOL.COM','3423565');
INSERT INTO CLIENTE VALUES(NULL,'ELAINE','M','ELAINE@GLOBO.COM','32567763');
INSERT INTO CLIENTE VALUES(NULL,'CARMEM','M','CARMEM@IG.COM','787832213');
INSERT INTO CLIENTE VALUES(NULL,'ADRIANA','F','ADRIANA@GMAIL.COM','88556942');
INSERT INTO CLIENTE VALUES(NULL,'JOICE','F','JOICE@GMAIL.COM','55412256');

/* CADASTRE UM ENDERECO PARA CADA CLIENTE */

INSERT INTO ENDERECO VALUES(NULL,'RUA GUEDES','CASCADURA','B. HORIZONTE','MG',10);
INSERT INTO ENDERECO VALUES(NULL,'RUA MAIA LACERDA','ESTACIO','RIO DE JANEIRO','RJ',11);
INSERT INTO ENDERECO VALUES(NULL,'RUA VISCONDESSA','CENTRO','RIO DE JANEIRO','RJ',12);
INSERT INTO ENDERECO VALUES(NULL,'RUA NELSON MANDELA','COPACABANA','RIO DE JANEIRO','RJ',13);
INSERT INTO ENDERECO VALUES(NULL,'RUA ARAUJO LIMA','CENTRO','VITORIA','ES',14);
INSERT INTO ENDERECO VALUES(NULL,'RUA CASTRO ALVES','LEBLON','RIO DE JANEIRO','RJ',15);
INSERT INTO ENDERECO VALUES(NULL,'AV CAPITAO ANTUNES','CENTRO','CURITIBA','PR',16);
INSERT INTO ENDERECO VALUES(NULL,'AV CARLOS BARROSO','JARDINS','SAO PAULO','SP',17);
INSERT INTO ENDERECO VALUES(NULL,'ALAMEDA SAMPAIO','BOM RETIRO','CURITIBA','PR',18);
INSERT INTO ENDERECO VALUES(NULL,'RUA DA LAPA','LAPA','SAO PAULO','SP',19);
INSERT INTO ENDERECO VALUES(NULL,'RUA GERONIMO','CENTRO','RIO DE JANEIRO','RJ',20);
INSERT INTO ENDERECO VALUES(NULL,'RUA GOMES FREIRE','CENTRO','RIO DE JANEIRO','RJ',21);
INSERT INTO ENDERECO VALUES(NULL,'RUA GOMES FREIRE','CENTRO','RIO DE JANEIRO','RJ',22);

/* CADASTRE TELEFONES PARA OS CLIENTES */


INSERT INTO TELEFONE VALUES(NULL,'RES','68976565',10);
INSERT INTO TELEFONE VALUES(NULL,'CEL','99656675',10);
INSERT INTO TELEFONE VALUES(NULL,'CEL','33567765',12);
INSERT INTO TELEFONE VALUES(NULL,'CEL','88668786',12);
INSERT INTO TELEFONE VALUES(NULL,'COM','55689654',12);
INSERT INTO TELEFONE VALUES(NULL,'COM','88687979',13);
INSERT INTO TELEFONE VALUES(NULL,'COM','88965676',14);
INSERT INTO TELEFONE VALUES(NULL,'CEL','89966809',15);
INSERT INTO TELEFONE VALUES(NULL,'COM','88679978',16);
INSERT INTO TELEFONE VALUES(NULL,'CEL','99655768',17);
INSERT INTO TELEFONE VALUES(NULL,'RES','89955665',18);
INSERT INTO TELEFONE VALUES(NULL,'RES','77455786',19);
INSERT INTO TELEFONE VALUES(NULL,'RES','89766554',19);
INSERT INTO TELEFONE VALUES(NULL,'RES','77755785',20);
INSERT INTO TELEFONE VALUES(NULL,'COM','44522578',20);
INSERT INTO TELEFONE VALUES(NULL,'RES','77755785',21);
INSERT INTO TELEFONE VALUES(NULL,'COM','44522578',22);



DESC CLIENTE;
DESC ENDERECO;
DESC TELEFONE;

SELECT * FROM CLIENTE;
SELECT * FROM ENDERECO;
SELECT * FROM TELEFONE;


mysql> SELECT C.IDCLIENTE, C.NOME, C.SEXO, C.EMAIL, C.CPF, E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO,    
T.TIPO, T.NUMERO FROM CLIENTE C INNER JOIN ENDERECO E ON C.IDCLIENTE = E
.ID_CLIENTE INNER JOIN TELEFONE T ON C.IDCLIENTE = T.ID_CLIENTE;
+-----------+---------+------+--------------------+--------------+--------------------+----------------+----------------+--------+------+-----------+
| IDCLIENTE | NOME    | SEXO | EMAIL              | CPF          | RUA                | BAIRRO         | CIDADE         | ESTADO | TIPO | NUMERO    |
+-----------+---------+------+--------------------+--------------+--------------------+----------------+----------------+--------+------+-----------+
|         7 | CASSIO  | M    | CASSIO@OUTLOOK.COM | 70345678919  | RUA STA EFIGENIA   | JD CLAUDIA     | S B CAMPO      | SP     | CEL  | 966695313 |
|         6 | CELIA   | F    | CELIA@YAHOO.COM    | 60345678918  | RUA DOS BAIANOS    | ESTACIO        | RIO DE JANEIRO | RJ     | COM  | 080070070 |
|         2 | CARLOS  | M    | CARLOS@HOTMAIL.COM | 30345678914  | AV NORTE SUL       | JARDIM CAMBURI | VITORIA        | ES     | RES  | 43516032  |
|         4 | CLARA   | F    | NULL               | 40345678916  | AV PAULISTA        | CENTRO         | SAO PAULO      | SP     | CEL  | 984206159 |
|         4 | CLARA   | F    | NULL               | 40345678916  | AV PAULISTA        | CENTRO         | SAO PAULO      | SP     | COM  | 30305050  |
|         2 | CARLOS  | M    | CARLOS@HOTMAIL.COM | 30345678914  | AV NORTE SUL       | JARDIM CAMBURI | VITORIA        | ES     | RES  | 41206580  |
|         7 | CASSIO  | M    | CASSIO@OUTLOOK.COM | 70345678919  | RUA STA EFIGENIA   | JD CLAUDIA     | S B CAMPO      | SP     | CEL  | 708425624 |
|         3 | ANA     | F    | ANA@GMAIL.COM      | 120345678915 | AV CERVANEJA       | EIXO NORTE     | GOIANIA        | GO     | COM  | 809251942 |
|         7 | CASSIO  | M    | CASSIO@OUTLOOK.COM | 70345678919  | RUA STA EFIGENIA   | JD CLAUDIA     | S B CAMPO      | SP     | CEL  | 506238282 |
|        10 | FLAVIO  | M    | FLAVIO@IG.COM      | 4657765      | RUA GUEDES         | CASCADURA      | B. HORIZONTE   | MG     | RES  | 68976565  |
|        10 | FLAVIO  | M    | FLAVIO@IG.COM      | 4657765      | RUA GUEDES         | CASCADURA      | B. HORIZONTE   | MG     | CEL  | 99656675  |
|        12 | GIOVANA | F    | NULL               | 0876655      | RUA VISCONDESSA    | CENTRO         | RIO DE JANEIRO | RJ     | CEL  | 33567765  |
|        12 | GIOVANA | F    | NULL               | 0876655      | RUA VISCONDESSA    | CENTRO         | RIO DE JANEIRO | RJ     | CEL  | 88668786  |
|        12 | GIOVANA | F    | NULL               | 0876655      | RUA VISCONDESSA    | CENTRO         | RIO DE JANEIRO | RJ     | COM  | 55689654  |
|        13 | KARLA   | M    | KARLA@GMAIL.COM    | 545676778    | RUA NELSON MANDELA | COPACABANA     | RIO DE JANEIRO | RJ     | COM  | 88687979  |
|        14 | DANIELE | M    | DANIELE@GMAIL.COM  | 43536789     | RUA ARAUJO LIMA    | CENTRO         | VITORIA        | ES     | COM  | 88965676  |
|        15 | LORENA  | M    | NULL               | 774557887    | RUA CASTRO ALVES   | LEBLON         | RIO DE JANEIRO | RJ     | CEL  | 89966809  |
|        16 | EDUARDO | M    | NULL               | 54376457     | AV CAPITAO ANTUNES | CENTRO         | CURITIBA       | PR     | COM  | 88679978  |
|        17 | ANTONIO | F    | ANTONIO@IG.COM     | 12436767     | AV CARLOS BARROSO  | JARDINS        | SAO PAULO      | SP     | CEL  | 99655768  |
|        18 | ANTONIO | M    | ANTONIO@UOL.COM    | 3423565      | ALAMEDA SAMPAIO    | BOM RETIRO     | CURITIBA       | PR     | RES  | 89955665  |
|        19 | ELAINE  | M    | ELAINE@GLOBO.COM   | 32567763     | RUA DA LAPA        | LAPA           | SAO PAULO      | SP     | RES  | 77455786  |
|        19 | ELAINE  | M    | ELAINE@GLOBO.COM   | 32567763     | RUA DA LAPA        | LAPA           | SAO PAULO      | SP     | RES  | 89766554  |
|        20 | CARMEM  | M    | CARMEM@IG.COM      | 787832213    | RUA GERONIMO       | CENTRO         | RIO DE JANEIRO | RJ     | RES  | 77755785  |
|        20 | CARMEM  | M    | CARMEM@IG.COM      | 787832213    | RUA GERONIMO       | CENTRO         | RIO DE JANEIRO | RJ     | COM  | 44522578  |
|        21 | ADRIANA | F    | ADRIANA@GMAIL.COM  | 88556942     | RUA GOMES FREIRE   | CENTRO         | RIO DE JANEIRO | RJ     | RES  | 77755785  |
|        22 | JOICE   | F    | JOICE@GMAIL.COM    | 55412256     | RUA GOMES FREIRE   | CENTRO         | RIO DE JANEIRO | RJ     | COM  | 44522578  |
+-----------+---------+------+--------------------+--------------+--------------------+----------------+----------------+--------+------+-----------+
26 rows in set (0.01 sec)

/* RELATORIO GERAL DE TODOS OS CLIENTES (TELEFONE E ENDERECO) */

SELECT C.IDCLIENTE, C.NOME, C.SEXO, C.EMAIL, C.CPF,
	   E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO,
	   T.TIPO, T.NUMERO
 FROM CLIENTE C
 INNER JOIN ENDERECO E
 ON C.IDCLIENTE = E.ID_CLIENTE
 INNER JOIN TELEFONE T
 ON C.IDCLIENTE = T.ID_CLIENTE;


/* RELATORIO DE HOMENS */

SELECT C.IDCLIENTE, C.NOME, C.SEXO, C.EMAIL, C.CPF,
	   E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO,
	   T.TIPO, T.NUMERO
 FROM CLIENTE C
 INNER JOIN ENDERECO E
 ON C.IDCLIENTE = E.ID_CLIENTE
 INNER JOIN TELEFONE T
 ON C.IDCLIENTE = T.ID_CLIENTE
 WHERE SEXO = 'M';

/* RELATORIO DE MULHERES */

SELECT C.IDCLIENTE, C.NOME, C.SEXO, C.EMAIL, C.CPF, 
	   E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO, 
	   T.TIPO, T.NUMERO
 FROM CLIENTE C
 INNER JOIN ENDERECO E
 ON C.IDCLIENTE = E.ID_CLIENTE
 INNER JOIN TELEFONE T
 ON C.IDCLIENTE = T.ID_CLIENTE
 WHERE SEXO = 'F';

/* QUANTIDADE DE HOMENS E MULHERES*/

/*SEXO*/
SELECT COUNT(*) AS QUANTIDADE, SEXO
 FROM CLIENTE
 WHERE SEXO = 'M';

/*FEMININO*/
SELECT COUNT(*) AS QUANTIDADE, SEXO
 FROM CLIENTE
 WHERE SEXO = 'F';

/*GROUP DIVIDE ENTRE M E F UTILIZANDO AS 'PROJECAO'*/
SELECT COUNT(*) AS QUANTIDADE, SEXO
 FROM CLIENTE
 GROUP BY SEXO;

mysql> SELECT COUNT(*) AS QUANTIDADE, SEXO FROM CLIENTE GROUP BY SEXO;
+------------+------+
| QUANTIDADE | SEXO |
+------------+------+
|          9 | M    |
|         12 | F    |
+------------+------+
/*OU*/

SELECT SEXO, COUNT(*) 
 FROM CLIENTE
 GROUP BY SEXO;

mysql> SELECT SEXO, COUNT(*)  FROM CLIENTE GROUP BY SEXO;
+------+----------+
| SEXO | COUNT(*) |
+------+----------+
| M    |        9 |
| F    |       12 |
+------+----------+
/* ID E EMAIL DAS MULHERES QUE MOREM NO CENTRO DO RIO DE JANEIRO E NÃO TENHA CELULAR */


SELECT C.IDCLIENTE, C.NOME, C.SEXO, C.EMAIL,
	   E.BAIRRO, E.CIDADE, 
	   T.TIPO, T.NUMERO
 FROM CLIENTE C
 INNER JOIN ENDERECO E
 ON C.IDCLIENTE = E.ID_CLIENTE
 INNER JOIN TELEFONE T
 ON C.IDCLIENTE = T.ID_CLIENTE;


SELECT C.IDCLIENTE, C.NOME, C.SEXO, C.EMAIL,
	   E.BAIRRO, E.CIDADE, 
	   T.TIPO, T.NUMERO
 FROM CLIENTE C
 INNER JOIN ENDERECO E
 ON C.IDCLIENTE = E.ID_CLIENTE
 INNER JOIN TELEFONE T
 ON C.IDCLIENTE = T.ID_CLIENTE
 WHERE SEXO = 'F';


SELECT C.IDCLIENTE, C.NOME, C.SEXO, C.EMAIL,
	   E.BAIRRO, E.CIDADE, 
	   T.TIPO, T.NUMERO
 FROM CLIENTE C
 INNER JOIN ENDERECO E
 ON C.IDCLIENTE = E.ID_CLIENTE
 INNER JOIN TELEFONE T
 ON C.IDCLIENTE = T.ID_CLIENTE
 WHERE SEXO = 'F';


SELECT C.IDCLIENTE, C.NOME, C.SEXO, C.EMAIL,
	   E.BAIRRO, E.CIDADE, 
	   T.TIPO, T.NUMERO
 FROM CLIENTE C
 INNER JOIN ENDERECO E
 ON C.IDCLIENTE = E.ID_CLIENTE
 INNER JOIN TELEFONE T
 ON C.IDCLIENTE = T.ID_CLIENTE
 WHERE SEXO = 'F' 
 AND BAIRRO = 'CENTRO' AND CIDADE = 'RIO DE JANEIRO';

SELECT C.IDCLIENTE, C.NOME, C.SEXO, C.EMAIL,
	   E.BAIRRO, E.CIDADE, 
	   T.TIPO, T.NUMERO
 FROM CLIENTE C
 INNER JOIN ENDERECO E
 ON C.IDCLIENTE = E.ID_CLIENTE
 INNER JOIN TELEFONE T
 ON C.IDCLIENTE = T.ID_CLIENTE
 WHERE SEXO = 'F' 
 AND (BAIRRO = 'CENTRO' AND CIDADE = 'RIO DE JANEIRO') 
 AND (TIPO = 'RES' OR TIPO = 'COM') ; --EMCAPSULAR VIRA UMA REGRA SO ISOLADA

/*SEM AS () QUE ISOLA A QUERY, TRAZENDO CONTEUDO A MAIS COMO SEXO M E OUTRO ENDERECO*/
--SEMPRE ISOLAR A QUERY QUNDO UTILIZAR A TABELA VERDADE COM OPERAD OR E AND
SELECT C.IDCLIENTE, C.NOME, C.SEXO, C.EMAIL,
	   E.BAIRRO, E.CIDADE, 
	   T.TIPO, T.NUMERO
 FROM CLIENTE C
 INNER JOIN ENDERECO E
 ON C.IDCLIENTE = E.ID_CLIENTE
 INNER JOIN TELEFONE T
 ON C.IDCLIENTE = T.ID_CLIENTE
 WHERE SEXO = 'F' 
 AND BAIRRO = 'CENTRO' AND CIDADE = 'RIO DE JANEIRO'
 AND TIPO = 'RES' OR TIPO = 'COM';

*-*-*-*-*

UPDATE

IDCLIENTE 13 14 15 19 20 = F
17 = M


/*APENAS UM*/
UPDATE CLIENTE SET SEXO = 'M'
 WHERE IDCLIENTE = 17;

/*UPDATE EM VARIOS ID METODO 1*/
UPDATE CLIENTE SET SEXO = 'F'
 WHERE IDCLIENTE = 13
 OR IDCLIENTE = 14
 OR IDCLIENTE = 15
 OR IDCLIENTE = 19
 OR IDCLIENTE = 20;

UPDATE CLIENTE SET SEXO = 'F'
 WHERE IDCLIENTE IN (13,14,15,19,20);

/*FILTRO*/
SELECT * FROM CLIENTE
 WHERE IDCLIENTE IN (13,14,15,19,20);

/*FILTRO*/
SELECT * FROM CLIENTE
 WHERE IDCLIENTE = 13
 OR IDCLIENTE = 14
 OR IDCLIENTE = 15
 OR IDCLIENTE = 19
 OR IDCLIENTE = 20;

 /* PARA UMA CAMPANHA DE MARKETING, O SETOR SOLICITOU UM RELATORIO COM NOME, EMAIL E TELEFONE CELULAR DOS CLIENTE 
 QUE MORAM NO ESTADO DO RIO DE JANEIRO. 
 VOCE TERA QUE PASSAR A QUERY PARA GERAR O RELATORIO PARA O PROGRAMADOR  */

SELECT C.IDCLIENTE, C.NOME, C.SEXO, C.EMAIL,
	   E.BAIRRO, E.CIDADE, E.ESTADO, 
	   T.TIPO, T.NUMERO
	   FROM CLIENTE C
	   INNER JOIN ENDERECO E
	   ON C.IDCLIENTE = E.ID_CLIENTE
	   INNER JOIN TELEFONE T
	   ON C.IDCLIENTE = T.ID_CLIENTE;


SELECT C.IDCLIENTE, C.NOME, C.SEXO, C.EMAIL, 	/*PROJECAO*/
	   E.BAIRRO, E.CIDADE, E.ESTADO, 
	   T.TIPO, T.NUMERO
	   FROM CLIENTE C 							/*ORIGEM*/
	   INNER JOIN ENDERECO E 					/*JUNCAO*/
	   ON C.IDCLIENTE = E.ID_CLIENTE			/*JUNCAO CONDICAO*/
	   INNER JOIN TELEFONE T 					/*JUNCAO*/
	   ON C.IDCLIENTE = T.ID_CLIENTE 			/*JUNCAO CONDICAO*/
	   WHERE ESTADO = 'RJ' AND TIPO = 'CEL';	/*SELECAO*/


 /* PARA UMA CAMPANHA DE PRODUTOS DE BELEZA, O COMERCIAL SOLICITOU UM RELATORIO COM NOME, EMAIL E TELEFONE CELULAR DAS MULHERES
 QUE MORAM NA CIDADE DE SAO PAULO. 
 VOCE TERA QUE PASSAR A QUERY PARA GERAR O RELATORIO PARA O PROGRAMADOR  */


SELECT C.IDCLIENTE,C.NOME, C.SEXO, C.EMAIL,
	   E.BAIRRO, E.CIDADE, E.ESTADO, 
	   T.TIPO, T.NUMERO
	   FROM CLIENTE C
	   INNER JOIN ENDERECO E
	   ON C.IDCLIENTE = E.ID_CLIENTE
	   INNER JOIN TELEFONE T
	   ON C.IDCLIENTE = T.ID_CLIENTE
	   WHERE SEXO = 'F' AND CIDADE = 'SAO PAULO';

IFNULL()

SELECT C.NOME, 
	   IFNULL(C.EMAIL,'NAO TEM EMAIL'),
	   T.NUMERO, 
	   E.ESTADO
 FROM CLIENTE C
 INNER JOIN TELEFONE T
 ON C.IDCLIENTE = T.ID_CLIENTE
 INNER JOIN ENDERECO E
 ON C.IDCLIENTE = E.ID_CLIENTE;


SELECT C.NOME, 
	   IFNULL(C.EMAIL,'****************') AS EMAIL,
	   T.NUMERO, 
	   E.ESTADO
 FROM CLIENTE C
 INNER JOIN TELEFONE T
 ON C.IDCLIENTE = T.ID_CLIENTE
 INNER JOIN ENDERECO E
 ON C.IDCLIENTE = E.ID_CLIENTE;

+---------+--------------------+-----------+--------+
| NOME    | EMAILS             | NUMERO    | ESTADO |
+---------+--------------------+-----------+--------+
| CASSIO  | CASSIO@OUTLOOK.COM | 966695313 | SP     |
| CELIA   | CELIA@YAHOO.COM    | 080070070 | RJ     |
| CARLOS  | CARLOS@HOTMAIL.COM | 43516032  | ES     |
| CLARA   | ****************   | 984206159 | SP     |
| CLARA   | ****************   | 30305050  | SP     |
| CARLOS  | CARLOS@HOTMAIL.COM | 41206580  | ES     |
| CASSIO  | CASSIO@OUTLOOK.COM | 708425624 | SP     |
| ANA     | ANA@GMAIL.COM      | 809251942 | GO     |
| CASSIO  | CASSIO@OUTLOOK.COM | 506238282 | SP     |
| FLAVIO  | FLAVIO@IG.COM      | 68976565  | MG     |
| FLAVIO  | FLAVIO@IG.COM      | 99656675  | MG     |
| GIOVANA | ****************   | 33567765  | RJ     |
| GIOVANA | ****************   | 88668786  | RJ     |
| GIOVANA | ****************   | 55689654  | RJ     |
| KARLA   | KARLA@GMAIL.COM    | 88687979  | RJ     |
| DANIELE | DANIELE@GMAIL.COM  | 88965676  | ES     |
| LORENA  | ****************   | 89966809  | RJ     |
| EDUARDO | ****************   | 88679978  | PR     |
| ANTONIO | ANTONIO@IG.COM     | 99655768  | SP     |
| ANTONIO | ANTONIO@UOL.COM    | 89955665  | PR     |
| ELAINE  | ELAINE@GLOBO.COM   | 77455786  | SP     |
| ELAINE  | ELAINE@GLOBO.COM   | 89766554  | SP     |
| CARMEM  | CARMEM@IG.COM      | 77755785  | RJ     |
| CARMEM  | CARMEM@IG.COM      | 44522578  | RJ     |
| ADRIANA | ADRIANA@GMAIL.COM  | 77755785  | RJ     |
| JOICE   | JOICE@GMAIL.COM    | 44522578  | RJ     |
+---------+--------------------+-----------+--------+
26 rows in set (0.00 sec)

mysql>


SELECT C.IDCLIENTE, 
	   C.NOME, 
	   C.CPF, 
	   C.EMAIL, 
	   T.TIPO, 
	   T.NUMERO, 
	   E.BAIRRO,
	   E.CIDADE, 
	   E.ESTADO, 
	   E.IDENDERECO, 
	   T.IDTELEFONE
 FROM CLIENTE C
 INNER JOIN TELEFONE T
 ON C.IDCLIENTE = T.ID_CLIENTE
 INNER JOIN ENDERECO E
 ON C.IDCLIENTE = E.ID_CLIENTE
 ORDER BY IDCLIENTE;

/*CRIANDO UMA CREATE VIEW */
CREATE VIEW V_RELATORIO AS
 SELECT C.IDCLIENTE, 
	   C.NOME,
	   C.SEXO, 
	   C.CPF,
	   IFNULL(C.EMAIL,'****************') AS EMAIL, 
	   T.TIPO, 
	   T.NUMERO, 
	   E.BAIRRO,
	   E.CIDADE, 
	   E.ESTADO, 
	   E.IDENDERECO, 
	   T.IDTELEFONE
 FROM CLIENTE C
 INNER JOIN TELEFONE T
 ON C.IDCLIENTE = T.ID_CLIENTE
 INNER JOIN ENDERECO E
 ON C.IDCLIENTE = E.ID_CLIENTE
 ORDER BY IDCLIENTE;

/* MOSTRAR CREATE VIEW */
SELECT * FROM RELATORIO;

/* PARA VISUALIZAR TODAS AS VIEW UTILIZAR O COMANDO SHOW TABLES*/

/* APAGANDO UMA VIEW */

DROP VIEW V_RELATORIO;

SHOW TABLES;

/*UTILIAZANDO UMA QUERY DENTRO DE OUTRA QUERY COM O COMANDO VIEW*/
SELECT IDCLIENTE ,NOME, NUMERO, ESTADO
	FROM V_RELATORIO;


SELECT NOME, SEXO, NUMERO, ESTADO
	FROM V_RELATORIO
	WHERE SEXO = 'F';

/*PRATICANDO ABAIXO */

CREATE TABLE GOVERNADORES(
 IDGOVERNADOR INT,
 NOME VARCHAR(20),
 ESTADO CHAR (2)
);

DROP TABLE GOVERNADORES ;

INSERT INTO GOVERNADORES VALUES (1,'CABRAL','RJ');
INSERT INTO GOVERNADORES VALUES (2,'DORIA','SP');
INSERT INTO GOVERNADORES VALUES (3,'ZEMA','MG');
INSERT INTO GOVERNADORES VALUES (4,'CASA GRANDE','ES');
INSERT INTO GOVERNADORES VALUES (5,'LEITE','RS');

CREATE VIEW V_GOVERNADORES AS
 SELECT NOME,ESTADO
 FROM GOVERNADORES;

SELECT * FROM V_GOVERNADORES;

SELECT * FROM GOVERNADORES;

SELECT * FROM V_GOVERNADORES
 WHERE NOME = 'CALCINHA APERTADA';

DELETE FROM V_GOVERNADORES
 WHERE NOME = 'DORIA';

SELECT * FROM GOVERNADORES
  WHERE NOME = 'DORIA';

UPDATE GOVERNADORES
 SET NOME = 'CALCINHA APERTADA'
 WHERE NOME = 'DORIA';

UPDATE V_GOVERNADORES
 SET NOME = 'DORIA'
 WHERE NOME = 'CALCINHA APERTADA';

INSERT INTO GOVERNADORES VALUES (2, 'DORIA','SP');
/*EXPLICACAO ABAIXO*/
INSERT INTO V_GOVERNADORES VALUES ('DORIA','SP');

/*
INSERT INTO GOVERNADORES VALUES (2, 'DORIA','SP') ;

CREATE TABLE GOVERNADORES(
 IDGOVERNADOR INT, -- CASO FOSSE INFORMADO NOT NULL NÃO SEIRA POSSIVEL APLICAR INSERT PELO VIEW
 NOME VARCHAR(20),
 ESTADO CHAR (2)
);

/*FICAR ATENTO AO REALIZAR INSERT NO EX ABAIXO NÃO PERMITE INSERIR O ID, NESSE CASO 
DEVE INFORMAR O ID SOMENTE NA TABELA DE CIMA DIRETO NA TABELA GOVERNADORES PQ V_GOVERNADORES
NÃO FOI CONFIGURADO O IDGOVERNADOR NA CRIACAO DA VIEW

INSERT INTO V_GOVERNADORES VALUES ('DORIA','SP') ;

CREATE VIEW V_GOVERNADORES AS
 SELECT NOME,ESTADO
 FROM GOVERNADORES;
*/

ALTER TABLE GOVERNADORES  
 CHANGE IDGOVERNADORES IDGOVERNADOR INT;

/* NÃO É POSSIVEL REALIZAR COMANDO DDL EM VIEW COM JOIN EX COMO INSERT E DELETE EXCETO UPDATE

A VIER É UM PONTEIRO ELA VAI NA TABELA E ALTERA MAIS O UPDATE É PERMITIDO 



*/