CREATE DATABASE LOJA;

USE LOJA;

CREATE TABLE PRODUTO(
	IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	VALOR FLOAT(10,2)
);

CREATE DATABASE BACKUP;

USE BACKUP;

/*QUANDO*/
SELECT NOW();
/*QUEM*/
SELECT CURRENT_USER();

USE BACKUP;

CREATE TABLE BKP_PRODUTO(
	IDBKP INT PRIMARY KEY AUTO_INCREMENT,
	IDPRODUTO INT,
	NOME VARCHAR(30),
	VALOR_ORIGINAL FLOAT(10,2),
	VALOR_ALTERADO FLOAT(10,2),
	DATA DATETIME,
	USUARIO VARCHAR(30),
	EVENTO CHAR(3)
);

/*UPDATE*/
CREATE TRIGGER AUDIT_PROD
 	AFTER UPDATE ON PRODUTO
	FOR EACH ROW
		BEGIN
			INSERT INTO BACKUP.BKP_PRODUTO VALUES(NULL,OLD.IDPRODUTO,OLD.NOME,OLD.VALOR,NEW.VALOR,NOW(),CURRENT_USER(),'UPD');
		END
	$

/*INSERT*/
CREATE TRIGGER AUDIT_PROD_INS
 	BEFORE INSERT ON PRODUTO
	FOR EACH ROW
		BEGIN
			INSERT INTO BACKUP.BKP_PRODUTO VALUES(NULL,NEW.IDPRODUTO,NEW.NOME,NEW.VALOR,NULL,NOW(),CURRENT_USER(),'INS');
		END
	$

/*DELETE*/
CREATE TRIGGER AUDIT_PROD_DEL
 	BEFORE DELETE ON PRODUTO
	FOR EACH ROW
		BEGIN
			INSERT INTO BACKUP.BKP_PRODUTO VALUES(NULL,OLD.IDPRODUTO,OLD.NOME,OLD.VALOR,NULL,NOW(),CURRENT_USER(),'DEL');
		END
	$

/*INSERINDO REGISTRO*/

INSERT INTO PRODUTO VALUES(NULL,'A PRIMEIRA',00.00);
INSERT INTO PRODUTO VALUES(NULL,'UTILIZANDO TRIGGER',50.00);
INSERT INTO PRODUTO VALUES(NULL,'LIVRO DE SQL',70.00);
INSERT INTO PRODUTO VALUES(NULL,'COMANDOS DML',530.00);
INSERT INTO PRODUTO VALUES(NULL,'UTILIZANDO OS JOINS',10.00);
INSERT INTO PRODUTO VALUES(NULL,'TESTE BACKUP',11.11);
INSERT INTO PRODUTO VALUES(NULL,'TRIGGER BACKUP',22.22);

INSERT INTO PRODUTO VALUES(NULL,'TESTE TRIGGER VOL1',33.33);
INSERT INTO PRODUTO VALUES(NULL,'TESTE TRIGGER VOL2',44.44);
INSERT INTO PRODUTO VALUES(NULL,'TESTE TRIGGER VOL3',55.55);
INSERT INTO PRODUTO VALUES(NULL,'TESTE TRIGGER VOL4',66.66);
INSERT INTO PRODUTO VALUES(NULL,'TESTE TRIGGER VOL5',01.01);

INSERT INTO PRODUTO VALUES(NULL,'TESTE TRIGGER VOL6',02.02);
INSERT INTO PRODUTO VALUES(NULL,'TESTE TRIGGER VOL7',03.03);
INSERT INTO PRODUTO VALUES(NULL,'TESTE TRIGGER VOL8',04.04);
INSERT INTO PRODUTO VALUES(NULL,'TESTE TRIGGER VOL9',03.03);
INSERT INTO PRODUTO VALUES(NULL,'TESTE TRIGGER VOL10',04.04);


INSERT INTO PRODUTO VALUES(NULL,'TESTE TRIGGER VOL11',05.08);
INSERT INTO PRODUTO VALUES(NULL,'TESTE TRIGGER VOL12',06.09);
INSERT INTO PRODUTO VALUES(NULL,'TESTE TRIGGER VOL13',07.10);
INSERT INTO PRODUTO VALUES(NULL,'TESTE TRIGGER VOL14',05.11);
INSERT INTO PRODUTO VALUES(NULL,'TESTE TRIGGER VOL15',08.12);

INSERT INTO PRODUTO VALUES(NULL,'TESTE TRIGGER VOL16 teste',09.13);

DELIMITER $
DELIMITER ;


UPDATE PRODUTO SET VALOR = 40.99
	WHERE IDPRODUTO = 12;

UPDATE PRODUTO SET VALOR = 100.00
	WHERE IDPRODUTO IN (8,9,10,11,12);

/*FILTRO*/
SELECT * FROM PRODUTO
	WHERE IDPRODUTO IN (8,9,10,11,12);

/*APAGAR OS DROP*/
DROP TRIGGER AUDIT_PROD_INS;
DROP TRIGGER AUDIT_PROD_DEL;

/*DELETAR EM QUANTIDADE*/
DELETE FROM PRODUTO
	WHERE IDPRODUTO IN (18,19,20,21,22);

DELETE FROM PRODUTO WHERE IDPRODUTO = 6;