-- Geração de Modelo físico
-- Sql ANSI 2003 - brModelo.



CREATE TABLE LIVROS (
ANO PUBLICACAO CHAR(4),
ESTADO (UF) DA EDITORA CHAR(2),
NOME DO LIVRO VARCHAR(30),
NOME DO AUTOR VARCHAR(30),
SEXO DO AUTOR VARCHAR(10),
NUMERO DE PAGINAS NUMERIC(5),
NOME DA EDITORA VARCHAR(15),
VALOR DO LIVRO INTEGER
)

